version: '3.7'

services:
  web:
    build: .
    command: python /django_for_professionals/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=%$$qcdbmywd(qhnllsq!v86b1vyw6%+b3sxaw@8!m$$^z*cubet9
      - DEBUG=1
    volumes:
      - .://django_for_professionals
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: