version: '3.7'

services:
  web:
    build: .
    command: python /django_for_professionals/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=%$$qcdbmywd(qhnllsq!v86b1vyw6%+b3sxaw@8!m$$^z*cubet9
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_c4jwQw498ceSHdIThzm9yLjB00kiBoO2GZ
      - STRIPE_TEST_SECRET_KEY=sk_test_GFWnqfkXZYL2pyx8JYVqP9Vq00v6yVVUuK
    volumes:
      - .://django_for_professionals
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11